version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - "/application_stack_data/redis:/data"
  
  web:
    image: localhost:5000/flask-redis-app:latest
    container_name: flask_app_canary
    ports:
      - "8002:8000"  # Canary instance on a different port
    depends_on:
      - redis
